// <auto-generated />
namespace CourseChentsov.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class EditUserLogins2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditUserLogins2));
        
        string IMigrationMetadata.Id
        {
            get { return "202005101855072_EditUserLogins2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
